### ISSUE TITLE
Love to compile this, but to many missing/outdated dependencies

### ISSUE THREAD

**Issue by piejanssens** [colinhumber/SickBeard-iOS#2]
Using an iPhone 5 with dev account.
I really like to compile this but after 3 hours of trying to fix all the dependencies and deprecated errors/warnings I gave up.

Could you please download this from Git yourself and see what's broken and update the code so that it works again. 

There is also something wrong with the .submodules, two last ones refer to your own Git repo which I don't have private keys for (that's the error I get).

**Comment by colinhumber** [comment]
Hey dude, sorry for the extended delay. I fixed the submodule issues and you should be able to clone everything fine now. Best to clone the main repo from scratch then pull the submodules again just to ensure everything is in sync.

**Comment by piejanssens** [comment]
OK gonna try it later today, I'll let you know if it worked out ok.
I'm iCouchPotato's dev btw ;-)

**Comment by colinhumber** [comment]
Oh right on! Sorry again for the delay. I hadn't looked at the repo in a
couple weeks.

On Wed, Dec 19, 2012 at 1:03 AM, Pieter Janssens
notifications@github.comwrote:

> OK gonna try it later today, I'll let you know if it worked out ok.
> I'm iCouchPotato's dev btw ;-)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/colinhumber/SickBeard-iOS/issues/2#issuecomment-11520829.

## 

Colin

**Comment by piejanssens** [comment]
Works great!

**Comment by roy** [comment]
I also just cloned this repo and it worked perfectly. 
Thanks :)
