### ISSUE TITLE
Usable without developer account?

### ISSUE THREAD

**Issue by frdmn** [colinhumber/SickBeard-iOS#4]
I just successfully compiled SickBeard iOS after i got rid of a little problem with the git submodules. I located the .ipa file and dropped it onto my iPhone 4 (iOS 7). 

The sync worked fine but now it stuck on "Waiting ..." as you can see in the screenshot below:

![cd5d2288-2a05-4d7a-a7bb-d9c22d826b8e](https://f.cloud.github.com/assets/944459/1187660/f7fd9a1e-238f-11e3-8cfd-a30882f38a8e.png)

Now i think i ran into those problems because i don't have an Apple Developer account. Is it even possible to use SickBeard iOS without one?

**Comment by colinhumber** [comment]
Unfortunately it's not possible. When you install an app on your device, even for testing purposes, Apple requires your device ID to be registered, either on your own developer account or on someone else's. I do have some spaces available on my developer account and can send you the build via TestFlight, the testing service I use. If you send your email address to sickbeardios@gmail.com, I'll send you an invite.

**Comment by frdmn** [comment]
That's awesome. i just sent you my e-mail!
