### ISSUE TITLE
Won't run on iPhone 5s

### ISSUE THREAD

**Issue by lukeadair** [colinhumber/SickBeard-iOS#8]
I'm able to get the project to build when selecting "iPhone Retina (4-inch)" but not "iPhone Retina (4-inch 64-bit)".

I would really love to be able to use your app. It looks great!

Heres my error log: http://pastebin.com/PLXpvPu3

Thanks,
Luke

**Comment by colinhumber** [comment]
I'll have a look! Just to check, you've installed the cocoa pods and all other dependencies?

**Comment by lukeadair** [comment]
Yes, I've installed all the dependencies. I also managed to get it to build
by changing some of the build settings related to architecture. I'm not in
front if it right now, so I'm not sure which ones. Thanks for this awesome
app!!

On another topic, have you considered submitting this to the App Store, or
even adding it to a cydia repo? It's just too awesome of an app to not
share.

Thanks,
Luke

**Comment by colinhumber** [comment]
Glad you've been enjoying it! I submitted it last year but it got rejected multiple times unfortunately. :( There is a private Cydia repo but I haven't had the time to update it with the latest ios7 supported version yet.

**Comment by colinhumber** [comment]
Updated the Pods versions and added the arm64 arch. Should be able to pull and build without any issues now!
