### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by iFredOS** [colinhumber/SickBeard-iOS#9]
I have Xcode 6 beta 2 with OS X 10.10. I followed your instructions but the pod don't seems to work with your code. 

After I did "pod install" I get this message:
### Stack

```
   CocoaPods : 0.29.0
        Ruby : ruby 2.0.0p451 (2014-02-24 revision 45167) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10 (14A261i)
       Xcode : 6.0 (6A216f)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9cfd689a97b0ffcd5bf6295c8fddbe6a3796eec7
```
### Podfile

``` ruby
platform :ios, '7.0'

pod 'AFNetworking'
pod 'SAMBadgeView'
pod 'SVProgressHUD'
pod 'SVSegmentedControl'
pod 'SAMWebView'
pod 'TSMessages'
pod 'SDWebImage'
```
### Error

```
Psych::SyntaxError - (/Users/fcote/.cocoapods/repos/master/CocoaPods-version.yml): mapping values are not allowed in this context at line 3 column 4
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0/gems/psych-2.0.5/lib/psych.rb:370:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0/gems/psych-2.0.5/lib/psych.rb:370:in `parse_stream'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0/gems/psych-2.0.5/lib/psych.rb:318:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0/gems/psych-2.0.5/lib/psych.rb:245:in `load'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0/gems/psych-2.0.5/lib/psych.rb:464:in `block in load_file'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0/gems/psych-2.0.5/lib/psych.rb:464:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0/gems/psych-2.0.5/lib/psych.rb:464:in `load_file'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.29.0/lib/cocoapods/sources_manager.rb:261:in `version_information'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.29.0/lib/cocoapods/sources_manager.rb:222:in `repo_compatible?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.29.0/lib/cocoapods/sources_manager.rb:281:in `master_repo_functional?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.29.0/lib/cocoapods/command.rb:39:in `parse'
/Library/Ruby/Gems/2.0.0/gems/claide-0.4.0/lib/claide/command.rb:179:in `parse'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.29.0/lib/cocoapods/command.rb:38:in `parse'
/Library/Ruby/Gems/2.0.0/gems/claide-0.4.0/lib/claide/command.rb:211:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.29.0/lib/cocoapods/command.rb:51:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.29.0/bin/pod:24:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by colinhumber** [comment]
It looks like you're using an old version of CocoaPods (0.29). I'd recommend upgrading to the latest version (0.33.1). I just tested with the latest gem version and it works. Failing that, it could be an issue with pod repo. There was a ticket on the CocoaPods repo regarding this error.

https://github.com/CocoaPods/CocoaPods/issues/1853

**Comment by iFredOS** [comment]
I redid "sudo gem install cocoa pods" (trust me I did it but didn't work and now it is. I don't understand why) and erased the /.cocoapods/ before the "pod install" and it fixed all my problems. Thanks!

**Comment by colinhumber** [comment]
Cheers! Glad it's working!

**Comment by iFredOS** [comment]
I cheered up too fast. Xcode cannot find the pods

The file “Pods.xcconfig” couldn’t be opened because there is no such file. (/Users/fcote/Documents/Xcode_Projets/SickBeard-iOS/Pods/Pods.xcconfig)

The file is there. What do you think is the issue now?

**Comment by iFredOS** [comment]
![screen shot 2014-06-29 at 18 12 57](https://cloud.githubusercontent.com/assets/732811/3424640/8cfeeca4-ffda-11e3-8608-a9c1cccf30f7.png)

**Comment by colinhumber** [comment]
Are you opening and compiling the Sickbeard.xcworkspace? Can you paste the entire compile log where you’re seeing that error?
On June 29, 2014 at 4:12:35 PM, iFredOS (notifications@github.com) wrote:

I cheered up too fast. Xcode cannot find the pods

The file “Pods.xcconfig” couldn’t be opened because there is no such file. (/Users/fcote/Documents/Xcode_Projets/SickBeard-iOS/Pods/Pods.xcconfig)

The file is there. What do you think is the issue now?

**Comment by iFredOS** [comment]
This is what I did.

![screen shot 2014-06-29 at 20 09 47](https://cloud.githubusercontent.com/assets/732811/3424868/f2ace51e-ffea-11e3-844c-03ef89dd2369.png)

**Comment by colinhumber** [comment]
This might be an issue with Xcode 6. I’ve seen those errors on SDWebImage before when compiling. Since Xcode 6 is still in beta I’m not officially supporting it. Try it on Xcode 5. iOS 7 and Xcode 5 are the officially supported OS and IDE versions.

-- 
Colin

On June 29, 2014 at 6:10:33 PM, iFredOS (notifications@github.com) wrote:

This is what I did.

**Comment by papertigers** [comment]
I can confirm that these errors are still in the official xcode 6 release.

**Comment by papertigers** [comment]
I believe this is because they are setting the getter method, so inside of the implementation you need to @synthesize the properties to _finished and _executing.

**Comment by colinhumber** [comment]
I've run into this before. I just need to update the version referenced in the Podfile.

**Comment by papertigers** [comment]
Cool.  I fixed it by synthesizing but your solution is probably the right one.
